name: Check version bumped
on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get old and new versions
        run: |
          # Version sur main
          git fetch origin main
          OLD_VERSION=$(git show origin/main:package.json | jq -r '.version')

          # Version sur la branche de la PR
          NEW_VERSION=$(jq -r '.version' package.json)

          echo "OLD_VERSION=$OLD_VERSION"
          echo "NEW_VERSION=$NEW_VERSION"

          if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
            echo "‚ùå package.json version must be bumped in this PR"
            exit 1
          fi

