name: Deploy psn-refresher Lambda

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prune dev deps
        run: npm prune --production

      - name: Zip artifact
        run: zip -r psn-fetcher.zip dist node_modules package.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update code (psn-refresher)
        run: |
          aws lambda update-function-code \
            --function-name trophyquest-psn-refresher \
            --zip-file fileb://psn-fetcher.zip

      - name: Wait for update to finish (psn-refresher)
        run: |
          aws lambda wait function-updated \
            --function-name trophyquest-psn-refresher

      - name: Publish version & update alias (psn-refresher)
        run: |
          VERSION=$(aws lambda publish-version \
            --function-name trophyquest-psn-refresher \
            --description "TrophyQuest Refresher v${{ steps.app_version.outputs.version }} - $GITHUB_SHA" \
            --query 'Version' --output text)
          
          aws lambda update-alias \
            --function-name trophyquest-psn-refresher \
            --name prod \
            --function-version $VERSION