name: Deploy psn-fetcher to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prune dev deps
        run: npm prune --production

      - name: Prepare lambda bundle
        run: |
          rm -rf lambda
          mkdir lambda
          cp package.json lambda/
          cp package-lock.json lambda/
          cp -r dist lambda/
          cp -r node_modules lambda/
          cd lambda
          zip -r ../lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update code (psn-fetcher)
        run: |
          aws lambda update-function-code \
            --function-name trophyquest-psn-fetcher \
            --zip-file fileb://lambda.zip

      - name: Wait for update to finish (psn-fetcher)
        run: |
          aws lambda wait function-updated \
            --function-name trophyquest-psn-fetcher

      - name: Publish version & update alias (psn-fetcher)
        run: |
          TQ_VERSION=$(jq -r '.version' package.json)
          
          LAMBDA_VERSION=$(aws lambda publish-version \
            --function-name trophyquest-psn-fetcher \
            --description "TrophyQuest Fetcher v$TQ_VERSION" \
            --query 'Version' --output text)
          
          aws lambda update-alias \
            --function-name trophyquest-psn-fetcher \
            --name prod \
            --function-version $LAMBDA_VERSION